#!/usr/bin/python3

import contextlib
from pathlib import Path
import re
import sys

import mdgen

out_path = Path(sys.argv[2]).absolute()

with contextlib.suppress(FileNotFoundError):
    out_path.chmod(0o600)


with open(sys.argv[1]) as rh, open(out_path, "w") as wh:
    for text in rh.readlines():
        text = mdgen.replace_md(text)
        print(text, file=wh, end="")

out_path.chmod(0o400)
