#!/bin/env python3

import contextlib
from pathlib import Path
import os
import sys

import mdgen

out_path = Path(sys.argv[2]).absolute()

source = os.path.abspath(sys.argv[1]).replace(os.path.abspath(mdgen.repository), "")

with open(sys.argv[1]) as rh:
    text = rh.read()

with contextlib.suppress(FileNotFoundError):
    out_path.chmod(0o600)

with open(out_path, "w") as out:
    text = mdgen.replace_md(text, source=source)
    print("> **DEPRECATION NOTICE**<br>", file=out)
    print(
        "> YOMM2 has been superseded by Boost.OpenMethod. See README for more details.\n",
        file=out,
    )
    print(text, file=out, end="")

out_path.chmod(0o400)
